In [17]:
import time 
import numpy as np 

In [7]:
# creating array from list 
arr_1d = np.array([1,3,4,5,6])
print("1D array :",arr_1d)

1D array : [1 3 4 5 6]


In [11]:
arr_2d = np.array( [[1,3,4],[5,6,2]])
print("2D array :", arr_2d)

2D array : [[1 3 4]
 [5 6 2]]


In [ ]:
##list vs numpy array 

py_list = [1,2,3,4]
print("list multiplication:", py_list*2)

arr = np.array([1,3,34,4])
print("array multi. :" , arr*2)

list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
array multi. : [ 2  6 68  8]


In [22]:
start = time.time() 

py_list = [ i*2 for i in range(1000000)]
print("\n list operation time : " , time.time()-start)


start = time.time()
np_array = np.arange(10000)*2
print("\n list operation time : " , time.time()-start)



 list operation time :  0.10865473747253418

 list operation time :  0.010007381439208984


In [27]:
# creating array from scratch 
zeros = np.zeros([3,4])
print( " zeros array :\n" , zeros)

ones = np.ones([3,4])
print( " Ones array :\n" , ones)

full = np.full((3,3), 6)
print( " full array :\n" , full)

random = np.random.random((2,3))
print( " random array :\n" , random)


sequence = np.arange(0, 10 , 2)
print( "sequesce array :\n" , sequence)

 zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 Ones array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 full array :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
 random array :
 [[0.02174847 0.65858926 0.29814182]
 [0.58002813 0.55800789 0.45453571]]
sequesce array :
 [0 2 4 6 8]


In [36]:
# vector , matrix , tensor

vector = np.array ([ 2,4,4])
print(vector,"\n_____" )


matrix = np.array([[1,2,3],[4,5,6]])
print(matrix ,"\n_____")


tensor = np.array([[[1,2] , [
    2,3]],
                   [[4,5] , [6,7]]])
print(tensor,"\n_____")

[2 4 4] 
_____
[[1 2 3]
 [4 5 6]] 
_____
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]] 
_____


In [ ]:
# array properties 