In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("+++ ZOMATO SALES ANALYSIS +++")
print("\n Sales Data shape:" , sales_data.shape)

print("\n Sample data for first 3 restaurants:")
print(sales_data[0:3])

+++ ZOMATO SALES ANALYSIS +++

 Sales Data shape: (5, 5)

 Sample data for first 3 restaurants:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
