In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("+++ ZOMATO SALES ANALYSIS +++")
print("\n Sales Data shape:" , sales_data.shape)

print("\n Sample data for first 3 restaurants:")
print(sales_data[0:3])
print("\n ")

+++ ZOMATO SALES ANALYSIS +++

 Sales Data shape: (5, 5)

 Sample data for first 3 restaurants:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 


In [28]:
# total salse per year 
print(np.sum(sales_data, axis = 0 ))
yearly_total = np.sum(sales_data[:, 1:], axis=0)
print("\n Total sales per year:")
print(yearly_total)


# minimum sales per restaurant
print("\n Minimum sales per restaurant:")
min_sales= np.min(sales_data[: , 1:], axis= 1)
print(min_sales)

# max sales per year 
print("\n Maximum sales per year:")
max_sales = np.max(sales_data[:, 1:], axis= 0)
print(max_sales)

#avg sales per reataurant 
print("\n Average sales per restaurant:")
avg_sales  = np.mean(sales_data[:, 1:], axis = 1)
print(avg_sales)

# cummulative 
cumsum = np.cumsum(sales_data[: , 1:], axis = 1)
print("\n Cumulative sales per restaurant:")
print(cumsum)

[     15  810000  945000 1085000 1240000]

 Total sales per year:
[ 810000  945000 1085000 1240000]

 Minimum sales per restaurant:
[150000 120000 200000 180000 160000]

 Maximum sales per year:
[200000 230000 260000 300000]

 Average sales per restaurant:
[200000. 152500. 247500. 225000. 195000.]

 Cumulative sales per restaurant:
[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
