In [1]:
import numpy as np

In [5]:
arr = np.array([
    [1,2,3],
    [4,5,6]    
    ])
print("shape:", arr.shape)
print("dimension", arr.ndim)
print("size", arr.size)
print("dtype", arr.dtype)

shape: (2, 3)
dimension 2
size 6
dtype int32


In [27]:
arr1= np.array(range(12))
print("original array:", arr1)
reshaped=arr1.reshape((3,4)) 
print("reshaped array :\n",reshaped )

print("flattend array:", arr1.flatten())

# it returns the view instead of copy of arr1
print("raveled:", arr1.ravel())

print("transpose\n",reshaped.T )




original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [29]:
## NUMPY ARRAY OPERATION

In [30]:
arr = np.array(range(1, 11))
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
print("basic slicing", arr[1:7:2])
print("negative slicing", arr[:-3:2])

basic slicing [2 4 6]
negative slicing [1 3 5 7]


In [32]:
arr_2d= np.array([
                [1,3,5],
                [54,33,77],
                [33,7,1]    
])

In [33]:
print("Specific element:", arr_2d[1,2])
print("entire row:", arr_2d[1])
print("entire row:", arr_2d[:,1])

Specific element: 77
entire row: [54 33 77]
entire row: [ 3 33  7]


In [34]:
unsorted =  np.array([3,5,2,66,43,3,444,87,5,2,5,85,4])
print("SORTED:",np.sort(unsorted))

SORTED: [  2   2   3   3   4   5   5   5  43  66  85  87 444]


In [35]:
arr_2d_unsorted= np.array([
                [3,44], [ 1,2 ], [2,3]    
])

print(arr_2d_unsorted)
print("sorted  2d array by column:\n", np.sort(arr_2d_unsorted,axis =0))



print("sorted  2d array by rows:\n", np.sort(arr_2d_unsorted,axis =1))

[[ 3 44]
 [ 1  2]
 [ 2  3]]
sorted  2d array by column:
 [[ 1  2]
 [ 2  3]
 [ 3 44]]
sorted  2d array by rows:
 [[ 3 44]
 [ 1  2]
 [ 2  3]]


In [44]:
numbers = np.array([1,2,3,4,5,6,7,8,10])
even_number  = numbers[numbers % 2 ==0]
print(even_number) 

[ 2  4  6  8 10]


In [45]:
mask = numbers >5
print("number greater than 5 : \n", numbers[mask])

number greater than 5 : 
 [ 6  7  8 10]


In [46]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("np where", numbers[where_result])

[1 3 5]
np where [ 6  7  8 10]


In [49]:
condition_array = np.where(numbers>5, numbers*4, numbers)
print(condition_array)

# if (numbers >5):
#        numbers*4
#    else : 
#        numbers 


[ 1  2  3  4  5 24 28 32 40]


In [51]:
condition_array = np.where(numbers>5,True,False)
print(condition_array)

[False False False False False  True  True  True  True]


In [55]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


In [63]:
original = np.array([ 
                    [1,2],
                    [3,4] 
                    ])
print("original\n",original)
new_row= np.array([[5,6]])
with_new_row= np.vstack((original, new_row))
print("with new row\n",with_new_row)

new_col= np.array([[7],[8]])
with_new_col= np.hstack((original, new_col))
print("with new col\n",with_new_col)

original
 [[1 2]
 [3 4]]
with new row
 [[1 2]
 [3 4]
 [5 6]]
with new col
 [[1 2 7]
 [3 4 8]]
