In [5]:
import numpy as np
import matplotlib.pyplot as plt

import day2A as d2
from day2A import sales_data

In [6]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])
print("\n Vector 1:", vector1)
print("Vector 2:", vector2)
print("\nAddition:", vector1 + vector2)
print("\nMultiplication:", vector1 * vector2)
print("\n Dot Product:", np.dot(vector1, vector2))

angle  = np.arccos(np.dot(vector1 , vector2)/ (np.linalg.norm(vector1)* np.linalg.norm(vector2)))
print("\n Angle between vector1 and vector2 (in radians):", angle)

 


 Vector 1: [1 2 3 4 5]
Vector 2: [ 6  7  8  9 10]

Addition: [ 7  9 11 13 15]

Multiplication: [ 6 14 24 36 50]

 Dot Product: 130

 Angle between vector1 and vector2 (in radians): 0.26554161733900966


In [9]:
restaurant_types = np.array(["Italian", "Chinese", "Mexican", "Indian", "French"])

vectorized_upper = np.vectorize(str.upper)

print("\nOriginal restaurant types:", restaurant_types)

print("Uppercase restaurant types:", 

vectorized_upper(restaurant_types))

monthly_avg = sales_data[:, 1:]/12
print("\nMonthly average sales for each restaurant:\n", monthly_avg)



Original restaurant types: ['Italian' 'Chinese' 'Mexican' 'Indian' 'French']
Uppercase restaurant types: ['ITALIAN' 'CHINESE' 'MEXICAN' 'INDIAN' 'FRENCH']

Monthly average sales for each restaurant:
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
